import { MigrationInterface, QueryRunner } from "typeorm";

export class CompanyOwner1707054331071 implements MigrationInterface {
    name = 'CompanyOwner1707054331071'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user" ADD "isAutoGenerated" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "company" ADD "ownerId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" ADD CONSTRAINT "UQ_ee87438803acb531639e8284be0" UNIQUE ("ownerId")`);
        await queryRunner.query(`ALTER TABLE "company" ADD "ownerContactEmail" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "firstName" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "lastName" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" ADD CONSTRAINT "FK_ee87438803acb531639e8284be0" FOREIGN KEY ("ownerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "company" DROP CONSTRAINT "FK_ee87438803acb531639e8284be0"`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "lastName" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "firstName" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "ownerContactEmail"`);
        await queryRunner.query(`ALTER TABLE "company" DROP CONSTRAINT "UQ_ee87438803acb531639e8284be0"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "ownerId"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "isAutoGenerated"`);
    }

}
