import {
  Column,
  Entity,
  CreateDateColumn,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
  ManyToOne,
  OneToOne,
} from 'typeorm';
import { Exclude } from 'class-transformer';
import { RoleEntity } from 'src/roles/entities';
import { CompanyEntity } from 'src/companies/entities';

@Entity('user')
export class UserEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({
    nullable: true,
  })
  firstName: string;

  @Column({
    nullable: true,
  })
  lastName: string;

  @Column({
    unique: true,
  })
  email: string;

  @Exclude()
  @Column()
  password: string;

  @Column({
    nullable: true,
    unique: true,
  })
  phone: string;

  @Column({
    default: false,
  })
  isAutoGenerated: boolean;

  @ManyToOne(() => RoleEntity, (role) => role.users, { onDelete: 'SET NULL' })
  role: RoleEntity;

  @ManyToOne(() => CompanyEntity, (company) => company.employees, {
    nullable: true,
  })
  company: CompanyEntity;

  @OneToOne(() => CompanyEntity, (company) => company.owner)
  ownedCompany: CompanyEntity;

  @CreateDateColumn({ type: 'timestamptz' })
  createdAt: string;

  @UpdateDateColumn({ type: 'timestamptz' })
  updatedAt: string;
}
